name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        otp: [26]
        elixir: [1.16.2]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Cache _build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Install deps
        run: mix deps.get

      - name: Format
        run: mix format --check-formatted

      - name: Credo
        run: mix credo --strict

      - name: Dialyzer
        run: mix dialyzer

      - name: Test
        run: mix test

      - name: CI Bench (non-blocking with warnings)
        env:
          MIX_ENV: test
          BENCH_BASELINE: bench/ci_baseline.json
          BENCH_REGRESSION_THRESHOLD: "1.15"
        run: |
          echo '{"ref_fill_rect": 50.0, "ref_export_webp": 120.0}' > bench/ci_baseline.json
          mix run bench/ci_bench_check.exs
